<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Data\SearchData;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('string' ,TextType::class ,[
                'label' => 'Recherche' ,
                'required' => false ,
                'attr' => [
                    'placeholder' => 'votre recherche ..',
                ]
            ])
            ->add('categories', EntityType::class, [
                'label' => false,
                'required' => false,
                'class' => Categorie::class,
                'choice_label'=>'nomCategorie',
                'expanded' => true,
                'multiple' => true
            ])
            ->add('submit',SubmitType::class,
                [
                    'label' => 'Filtrer',
                    'attr' => [
                        'class' => 'rt-btn rt-gradient pill rt-sm3 text-uppercase rt-mt-10 btn-block'

                    ]
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SearchData::class ,
            'method' => 'GET' ,
            'csrf_protection' => false ,
        ]);
    }
    //data_class: classe li chn7ot fiha les donnees : searchdata :(
    public function getBlockPrefix()
    {
        return ''; // TODO: Change the autogenerated stub
    }}
